language: ruby
rvm:
  - '2.1.1'

before_script:
  - psql -c 'create database full_stack_talks_test;' -U postgres
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare

env:
  - MEETUP_API_KEY=123456789 APPLICATION_SECRET_TOKEN=1011011111110110111011110000110001
